import * as fs from "node:fs";
import * as path from "node:path";
import type { EndpointProfile } from "../endpoints/profile";
import type { EndpointForm, EndpointFormType } from "../ui/protocol";

/**
 * Writing and deleting endpoint YAML.
 *
 * The generated file is deliberately verbose: it is the primary documentation
 * a user meets, and the fields they will need next (mTLS, proxy, exchange auth)
 * ship commented out rather than absent, so the shape is discoverable without
 * leaving the editor.
 */

export const PROFILE_ID_RE = /^[\w][\w.-]*$/;

/**
 * The SecretStorage name a profile's API key lives under.
 *
 * `App` prefixes every lookup with `kryptonite.`, and `interpolate()` resolves
 * `${secret:<this>}` at request time. Keeping the derivation in one function is
 * what lets the YAML writer, the save handler and the pre-save check agree on
 * where the key is without passing it between them.
 */
export function secretKeyFor(id: string): string {
  return `${id}/api_key`;
}

/** Form provider type onto the real wire value. */
export function wireForType(type: EndpointFormType): "openai" | "anthropic" {
  return type === "anthropic" ? "anthropic" : "openai";
}

function defaultChatPath(type: EndpointFormType): string | undefined {
  // Anthropic and plain OpenAI-compatible gateways hit the loader defaults, so
  // writing chatPath would be noise. Azure and custom gateways almost never do.
  if (type === "azure") return "/openai/deployments/<deployment>/chat/completions";
  if (type === "custom") return "/v1/chat/completions";
  return undefined;
}

/**
 * Fallback only. The form now carries a model field, so this is what a profile
 * gets when the caller left it blank - a plausible id for the provider type,
 * not a promise that the gateway serves it.
 */
export function defaultModel(type: EndpointFormType): string {
  switch (type) {
    case "anthropic":
      return "claude-sonnet-4-5";
    case "local":
      return "qwen2.5-coder:14b";
    case "azure":
      return "gpt-4o";
    default:
      return "gpt-4o";
  }
}

function quote(v: string): string {
  // Any value containing YAML-significant characters gets quoted. A URL with a
  // colon is not safe bare; a plain identifier reads better without quotes.
  return /^[\w./-]+$/.test(v) ? v : JSON.stringify(v);
}

/**
 * Build the YAML body for a profile.
 *
 * `${env:…}` and `${secret:…}` must survive into the file verbatim - they are
 * resolved at request time by `interpolate()`, not here. They are written
 * inside normal strings so no template-literal escaping applies.
 */
export function renderProfileYaml(form: EndpointForm): string {
  const wire = wireForType(form.type);
  // An explicit route from the form always wins; the per-type default is only
  // a starting point for gateways that are known to prefix their routes.
  const chatPath = form.chatPath?.trim() || defaultChatPath(form.type);
  const model = form.model?.trim() || defaultModel(form.type);
  const local = form.type === "local";
  const displayName = form.name.trim() || form.id;

  const lines: string[] = [];
  lines.push(`# ${displayName}`);
  lines.push(`# Generated by KRYPTONITE. Edit freely - the file is the source of truth.`);
  lines.push(``);
  lines.push(`name: ${form.id}`);
  lines.push(`description: ${quote(displayName)}`);
  lines.push(`wire: ${wire}                      # openai | anthropic | raw`);
  lines.push(`baseUrl: ${quote(form.url)}`);
  lines.push(`model: ${model}`);
  lines.push(``);

  if (chatPath) {
    lines.push(`# Many gateways prefix their routes. Adjust this to match yours.`);
    lines.push(`chatPath: ${quote(chatPath)}`);
  } else {
    lines.push(`# chatPath: /v1/chat/completions   # only when the gateway prefixes its routes`);
  }
  lines.push(`timeoutMs: ${form.timeoutMs && form.timeoutMs > 0 ? Math.round(form.timeoutMs) : 120000}`);
  lines.push(`retries: 2`);
  if (form.http2) {
    lines.push(`http2: true                       # this gateway needs HTTP/2`);
  } else {
    lines.push(`# http2: true                      # some gateways stall on HTTP/1.1 POSTs`);
  }
  lines.push(``);

  lines.push(`# headers:                          # merged into every request`);
  lines.push(`#   X-Team: platform`);
  lines.push(`# query:                            # merged into the request URL`);
  lines.push(`#   api-version: "2026-02-01"`);
  lines.push(`# extraBody:                        # merged into every request body`);
  lines.push(`#   tenant: eng`);
  lines.push(`# transform: .agent/transforms/envelope-wrap.js   # required when wire: raw`);
  lines.push(``);

  const storedKey = Boolean(form.apiKey?.trim() || form.hasStoredKey);

  lines.push(`auth:`);
  if (local) {
    lines.push(`  kind: none                      # a local model needs no credential`);
  } else {
    lines.push(`  kind: bearer                    # none | bearer | header | exchange | exec`);
    if (storedKey) {
      // The key the user typed went to SecretStorage; the file only ever holds
      // the reference. This is the difference between a profile that can be
      // committed to the repo and one that leaks a credential on first push.
      lines.push(`  value: ` + "${secret:" + secretKeyFor(form.id) + "}");
      lines.push(`  # The key is in VS Code SecretStorage under`);
      lines.push(`  # kryptonite.${secretKeyFor(form.id)} - not in this file.`);
      lines.push(`  # Swap in ` + "${env:VAR}" + ` or ` + "${file:path}" + ` if you prefer.`);
    } else {
      lines.push(`  value: ` + "${env:KRYPTONITE_API_KEY}");
      lines.push(`  # Secrets never live in this file. Use ` + "${env:VAR}, ${secret:NAME}");
      lines.push(`  # (VS Code SecretStorage, key kryptonite.<NAME>) or ` + "${file:path}.");
    }
  }
  lines.push(`  #`);
  lines.push(`  # OAuth2 client-credentials instead:`);
  lines.push(`  # kind: exchange`);
  lines.push(`  # exchange:`);
  lines.push(`  #   url: https://sso.corp.example/oauth2/token`);
  lines.push(`  #   encoding: form`);
  lines.push(`  #   body:`);
  lines.push(`  #     grant_type: client_credentials`);
  lines.push(`  #     client_id: ` + "${env:GW_ID}");
  lines.push(`  #     client_secret: ` + "${secret:corp/client_secret}");
  lines.push(`  #   tokenPath: access_token`);
  lines.push(`  #   expiresInPath: expires_in`);
  lines.push(``);

  lines.push(`tls:`);
  if (local) {
    lines.push(`  # A loopback endpoint over http needs no TLS block at all.`);
    lines.push(`  # caBundle: system`);
  } else {
    lines.push(`  caBundle: [system]              # "system" pulls the OS trust store`);
    lines.push(`  # caBundle: [system, ~/certs/corp-root.pem]`);
  }
  lines.push(`  # cert: ~/certs/client.crt      # mTLS - cert and key must BOTH be set`);
  lines.push(`  # key: ~/certs/client.key`);
  lines.push(`  # keyPassphrase: ` + "${secret:corp/key_pass}");
  lines.push(`  # minVersion: TLSv1.2`);
  lines.push(`  # servername: gateway.corp.example`);
  lines.push(`  # insecureSkipVerify: true      # explicit opt-in only`);
  lines.push(``);

  lines.push(`proxy:`);
  if (local) {
    lines.push(`  useEnvironment: false           # never send loopback traffic to a proxy`);
  } else {
    lines.push(`  useEnvironment: true            # honour HTTPS_PROXY / NO_PROXY`);
    lines.push(`  # url: http://proxy.corp:8080`);
    lines.push(`  # noProxy: [.internal, localhost]`);
  }
  lines.push(``);

  lines.push(`capabilities:`);
  lines.push(`  streaming: true`);
  lines.push(`  tools: true`);
  lines.push(`  vision: false`);
  lines.push(`  systemRole: message             # message | top-level | prepend-user`);
  lines.push(`  contextWindow: ${local ? 32768 : 128000}`);
  lines.push(`  maxOutputTokens: 4096`);
  lines.push(`  tokenCounting: heuristic        # api | heuristic`);
  lines.push(`  parallelToolCalls: false`);
  lines.push(``);

  return lines.join("\n");
}

/** The starter file behind `newEndpoint`, before the user has named anything. */
export function newEndpointForm(): EndpointForm {
  return {
    id: "new-endpoint",
    name: "New endpoint",
    url: "https://gateway.internal.example",
    type: "openai-compatible",
  };
}

export interface SaveResult {
  file: string;
  /** Set when a rename removed the profile's previous file. */
  removed?: string;
}

/**
 * Write `<dir>/<id>.yaml`. On rename, the old profile's `sourceFile` is
 * deleted so the loader does not surface both copies as duplicate profiles.
 */
export function saveEndpointFile(
  dir: string,
  form: EndpointForm,
  profiles: EndpointProfile[]
): SaveResult {
  if (!PROFILE_ID_RE.test(form.id)) {
    throw new Error(
      `Invalid profile id "${form.id}". Use letters, digits, dot, dash or underscore, starting with a word character.`
    );
  }
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${form.id}.yaml`);
  fs.writeFileSync(file, renderProfileYaml(form), "utf8");

  let removed: string | undefined;
  const previousId = form.originalId;
  if (previousId && previousId !== form.id) {
    const old = profiles.find((p) => p.name === previousId);
    const oldFile = old?.sourceFile;
    if (oldFile && path.resolve(oldFile) !== path.resolve(file) && fs.existsSync(oldFile)) {
      try {
        fs.rmSync(oldFile);
        removed = oldFile;
      } catch {
        // Leaving the old file behind is recoverable; failing the save is not.
      }
    }
  }
  return { file, removed };
}

/**
 * Update keys inside a profile's `capabilities:` block, in place.
 *
 * Deliberately a line edit rather than parse-and-rerender. `renderProfileYaml`
 * builds a whole file from a form with fixed defaults, so routing a single
 * toggle through it would silently discard every hand-written setting and
 * comment in the file - including the ones somebody opened the YAML to write.
 * Only the lines being changed are touched.
 *
 * Keys already present are rewritten and keep their trailing comment; keys
 * absent are appended to the block. A file with no `capabilities:` block gets
 * one.
 */
export function setCapabilities(file: string, patch: Record<string, unknown>): void {
  const entries = Object.entries(patch);
  if (!entries.length) return;

  const src = fs.readFileSync(file, "utf8");
  const eol = src.includes("\r\n") ? "\r\n" : "\n";
  const lines = src.split(/\r?\n/);

  const head = lines.findIndex((l) => /^capabilities\s*:/.test(l));
  if (head === -1) {
    const block = ["", "capabilities:", ...entries.map(([k, v]) => `  ${k}: ${yamlScalar(v)}`)];
    fs.writeFileSync(file, lines.concat(block).join(eol), "utf8");
    return;
  }

  // The block runs until the first line that is neither indented nor blank.
  let end = head + 1;
  while (end < lines.length && (lines[end].trim() === "" || /^\s+\S/.test(lines[end]))) end++;

  const remaining = new Map(entries);
  for (let i = head + 1; i < end; i++) {
    const m = lines[i].match(/^(\s+)([A-Za-z_][\w-]*)\s*:\s*([^#]*?)\s*(#.*)?$/);
    if (!m || !remaining.has(m[2])) continue;
    const value = remaining.get(m[2]);
    remaining.delete(m[2]);
    // The trailing comment usually documents the allowed values, so it stays.
    lines[i] = `${m[1]}${m[2]}: ${yamlScalar(value)}${m[4] ? "  " + m[4] : ""}`;
  }

  if (remaining.size) {
    // Inserted before any trailing blank lines inside the block, so the file
    // does not grow a gap in the middle of it.
    let at = end;
    while (at > head + 1 && lines[at - 1].trim() === "") at--;
    lines.splice(at, 0, ...[...remaining].map(([k, v]) => `  ${k}: ${yamlScalar(v)}`));
  }

  fs.writeFileSync(file, lines.join(eol), "utf8");
}

function yamlScalar(v: unknown): string {
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  const s = String(v);
  // Quote anything YAML would otherwise read as a different type.
  return /^[A-Za-z][\w.-]*$/.test(s) ? s : JSON.stringify(s);
}

/** Create the starter profile unless the file already exists. */
export function createTemplateFile(dir: string): { file: string; created: boolean } {
  fs.mkdirSync(dir, { recursive: true });
  const form = newEndpointForm();
  const file = path.join(dir, "new-endpoint.yaml");
  if (fs.existsSync(file)) return { file, created: false };
  fs.writeFileSync(file, renderProfileYaml(form), "utf8");
  return { file, created: true };
}

/** Remove a profile's backing YAML. Returns the deleted path, if any. */
export function deleteEndpointFile(
  profiles: EndpointProfile[],
  id: string
): string | undefined {
  const profile = profiles.find((p) => p.name === id);
  const file = profile?.sourceFile;
  if (!file || !fs.existsSync(file)) return undefined;
  fs.rmSync(file);
  return file;
}
